// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kwjrUSXDQgP_DA6fPjTYpEJYqehYdiM',
    appId: '1:891812150665:web:2c941c2cad8a31e6b7f558',
    messagingSenderId: '891812150665',
    projectId: 'schoolman-proj',
    authDomain: 'schoolman-proj.firebaseapp.com',
    databaseURL: 'https://schoolman-proj-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolman-proj.appspot.com',
    measurementId: 'G-9Z53VG9FS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLu8TtYgeoWAGYukwh_lIU7FU1j0wgnPs',
    appId: '1:891812150665:android:ddbd3d0151537109b7f558',
    messagingSenderId: '891812150665',
    projectId: 'schoolman-proj',
    databaseURL: 'https://schoolman-proj-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolman-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxN8gxjD87W0LkW1rbGDdZo4XRXzCYkA',
    appId: '1:891812150665:ios:e528ad0f71015f93b7f558',
    messagingSenderId: '891812150665',
    projectId: 'schoolman-proj',
    databaseURL: 'https://schoolman-proj-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolman-proj.appspot.com',
    androidClientId: '891812150665-fa3os39nbcmecdi1dj1b4qfco5m73vf4.apps.googleusercontent.com',
    iosClientId: '891812150665-3o4tlf7565fh0klfhjbq9suqqe59rt7c.apps.googleusercontent.com',
    iosBundleId: 'com.n30gu1.SchoolMan',
  );
}
