// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnGYHPhdn0goHQnxo-G7AKeFDDmyYaDI',
    appId: '1:702977533556:web:c56b91820ac0b2aec45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    authDomain: 'proj-schoolman.firebaseapp.com',
    storageBucket: 'proj-schoolman.appspot.com',
    measurementId: 'G-09GGLJ014G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60eUGZJCz9_LtnmBF1qkzGeEg8wzD85Q',
    appId: '1:702977533556:android:74c71c4d2881daa3c45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    storageBucket: 'proj-schoolman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6e2XtSdgtcDNpNQKYRbFsI-Sut7X1IPs',
    appId: '1:702977533556:ios:c06ca79be03210e8c45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    storageBucket: 'proj-schoolman.appspot.com',
    iosClientId: '702977533556-sahiv9mnk66gkj6kpf4poncrmodlv0f0.apps.googleusercontent.com',
    iosBundleId: 'com.n30gu1.schoolman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6e2XtSdgtcDNpNQKYRbFsI-Sut7X1IPs',
    appId: '1:702977533556:ios:c06ca79be03210e8c45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    storageBucket: 'proj-schoolman.appspot.com',
    iosClientId: '702977533556-sahiv9mnk66gkj6kpf4poncrmodlv0f0.apps.googleusercontent.com',
    iosBundleId: 'com.n30gu1.schoolman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdnGYHPhdn0goHQnxo-G7AKeFDDmyYaDI',
    appId: '1:702977533556:web:a982c8f438a06dd1c45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    authDomain: 'proj-schoolman.firebaseapp.com',
    storageBucket: 'proj-schoolman.appspot.com',
    measurementId: 'G-20JY9MP82N',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDdnGYHPhdn0goHQnxo-G7AKeFDDmyYaDI',
    appId: '1:702977533556:web:d99c2d7d38d8a95ec45321',
    messagingSenderId: '702977533556',
    projectId: 'proj-schoolman',
    authDomain: 'proj-schoolman.firebaseapp.com',
    storageBucket: 'proj-schoolman.appspot.com',
    measurementId: 'G-H1ES7ECYTF',
  );
}
